### ISSUE TITLE
Mail: Fund balance warning mail is not being send

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1440]
## Context/goal: 
Fund balance warning is not being send.
Environment: producten
Status: needs testing

**Comment by maxvisser** [comment]
```
[2020-03-25 08:00:06] production.ERROR: Return value of App\Services\Forus\Notification\NotificationService::fundBalanceWarning() must be of the type bool, null returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Services\\Forus\\Notification\\NotificationService::fundBalanceWarning() must be of the type bool, null returned at /var/app/current/app/Services/Forus/Notification/NotificationService.php:952)
[stacktrace]
#0 /var/app/current/app/Models/Fund.php(987): App\\Services\\Forus\\Notification\\NotificationService->fundBalanceWarning('minima@socialed...', '0xcd20c276ba12e...', 'https://forus.i...', 'Gemeente Berkel...', 'Sociaal culture...', '454545.70', '454545.28', '************...', '****-****')
#1 /var/app/current/app/Console/Commands/NotifyAboutReachedNotificationFundAmount.php(42): App\\Models\\Fund::notifyAboutReachedNotificationAmount()
#2 [internal function]: App\\Console\\Commands\\NotifyAboutReachedNotificationFundAmount->handle()
#3 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#4 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#6 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#7 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#8 /var/app/current/vendor/laravel/framework/src/Illuminate/Console/Command.php(201): Illuminate\\Container\\Container->call(Array)
#9 /var/app/current/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#10 /var/app/current/vendor/laravel/framework/src/Illuminate/Console/Command.php(188): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#11 /var/app/current/vendor/symfony/console/Application.php(1012): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#12 /var/app/current/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\NotifyAboutReachedNotificationFundAmount), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 /var/app/current/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /var/app/current/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /var/app/current/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 {main}
"}
```

https://github.com/teamforus/forus-backend/blob/53d60092a1c7a7197a87c555e3a1eb96cd3dfe3a/app/Services/Forus/Notification/NotificationService.php#L952

**Comment by maxvisser** [comment]
We found the issue; now look into a fix
